DOCSP-16223 Drop support for zSeries platforms
mongodb/docs-bi-connector pull request #312
Opened 2021-05-26 21:01 UTC by kanchana-mongodb

- [JIRA](https://jira.mongodb.org/browse/DOCSP-16223)
- [Stage](url)

2021-05-26 22:07 UTC, rychipman requested changes

2021-05-26 22:07 UTC, rychipman commented on source/release-notes.txt
> +platforms. These zSeries platforms are no longer supported:
```suggestion
These zSeries platforms are no longer supported:
```

2021-05-26 22:07 UTC, rychipman commented on source/release-notes.txt
> +- ``ubuntu1804-zseries-*``
```suggestion
- ``RHEL 6.7 s390x``
- ``RHEL 7.2 s390x``
- ``SUSE 12 s390x``
- ``SUSE 15 s390x``
- ``Ubuntu 16.04 s390x``
- ``Ubuntu 18.04 s390x``
```

2021-05-27 18:44 UTC, rychipman approved these changes
LGTM

2021-05-27 20:58 UTC, JuliaMongo approved these changes
LGTM with one change requested.

2021-05-27 20:58 UTC, JuliaMongo commented on source/release-notes.txt
> +*Released <PLEASE UPDATE>, 2021*
To be safe, I suggest replacing this with May.

2021-06-01 22:10 UTC, merged