DOCSP-40387 Add Verification section to BI Connector installation pages
mongodb/docs-bi-connector pull request #436
Opened 2024-06-21 18:14 UTC by kanchana-mongodb

- [JIRA](https://jira.mongodb.org/browse/DOCSP-40387)
- Stage:
  - [Windows](https://preview-mongodbkanchanamongodb.gatsbyjs.io/bi-connector/DOCSP-40387/tutorial/install-bi-connector-windows/)
  - [Mac](https://preview-mongodbkanchanamongodb.gatsbyjs.io/bi-connector/DOCSP-40387/tutorial/install-bi-connector-macos/)
  - [RHEL](https://preview-mongodbkanchanamongodb.gatsbyjs.io/bi-connector/DOCSP-40387/tutorial/install-bi-connector-rhel/)
  - [Debian](https://preview-mongodbkanchanamongodb.gatsbyjs.io/bi-connector/DOCSP-40387/tutorial/install-bi-connector-debian/)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6675c12febce19f314ec8916)

2024-06-24 23:38 UTC, jchemburkar reviewed
This looks pretty good to me, just had one note! I also forwarded the link to @nbagnard as well to help look over

2024-06-24 23:38 UTC, jchemburkar commented on source/includes/steps-install-bi-connector-debian.yaml
> +  The MongoDB release team digitally signs all software packages to
Technically the SQL Engines team is the one signing / releasing these packges, we don't go through the release team to do so, so maybe worth updating this line (here and in the subsequent pages)?

2024-06-26 17:37 UTC, nbagnard requested changes

2024-06-26 17:37 UTC, nbagnard commented on source/includes/steps-install-bi-connector-debian.yaml
> +  MongoDB release. MongoDB signs each release branch with a different
```suggestion
  MongoDB release. The `bi-connector.asc` key to validate the BI Connector is available on [pgp.mongodb.com](https://pgp.mongodb.com/bi-connector.asc)  
```

2024-06-26 17:37 UTC, nbagnard commented on source/includes/steps-install-bi-connector-debian.yaml
> +  a. Run the following command to downloaded the ``.sig`` file.
```suggestion
  a. Run the following command to download the ``.sig`` file.
```

2024-06-26 17:37 UTC, nbagnard commented on source/includes/steps-install-bi-connector-debian.yaml
> +        curl -LO https://info-mongodb-com.s3.amazonaws.com/mongodb-bi/v2/mongodb-bi-linux-{arch}-{platform}-{version}.tgz.sig
Maybe we could add an example here. I think it won't be super straightforward for users to figure out the arch and platform.
Here is an example link `https://info-mongodb-com.s3.amazonaws.com/mongodb-bi/v2/mongodb-bi-linux-x86_64-suse12-v2.14.14.tgz.sig`

2024-06-26 17:37 UTC, nbagnard commented on source/includes/steps-install-bi-connector-macos.yaml
> +  MongoDB release. MongoDB signs each release branch with a different
```suggestion
  MongoDB release. The `bi-connector.asc` key to validate the BI Connector is available on [pgp.mongodb.com](https://pgp.mongodb.com/bi-connector.asc)  
```

2024-06-26 17:37 UTC, nbagnard commented on source/includes/steps-install-bi-connector-macos.yaml
> +        curl -LO https://info-mongodb-com.s3.amazonaws.com/mongodb-bi/v2/mongodb-bi-osx-{x86_64|arm64}-{version}.zip.sig
Here is are example links : 
- https://info-mongodb-com.s3.amazonaws.com/mongodb-bi/v2/mongodb-bi-osx-arm64-macos11-v2.14.14.zip.sig
- https://info-mongodb-com.s3.amazonaws.com/mongodb-bi/v2/mongodb-bi-osx-x86_64-v2.14.14.zip.sig
```suggestion
        curl -LO https://info-mongodb-com.s3.amazonaws.com/mongodb-bi/v2/mongodb-bi-osx-{x86_64|arm64-macos{11|13}}-{version}.zip.sig
```

2024-06-26 17:37 UTC, nbagnard commented on source/includes/steps-install-bi-connector-macos.yaml
> +        unzip {SOURCE-PATH}/mongodb-bi-osx-{x86_64|arm64}-{version}.zip -d {DESTINATION-PATH}
```suggestion
        unzip {SOURCE-PATH}/mongodb-bi-osx-{x86_64|arm64-macos{11|13}}-{version}.zip -d {DESTINATION-PATH}
```

2024-06-26 17:37 UTC, nbagnard commented on source/includes/steps-install-bi-connector-macos.yaml
> +  b. Change to the ``mongodb-bi-osx-{x86_64|arm64}-{version}`` directory.
```suggestion
  b. Change to the ``mongodb-bi-osx-{x86_64|arm64-macos{11|13}}-{version}`` directory.
```

2024-06-26 17:37 UTC, nbagnard commented on source/includes/steps-install-bi-connector-macos.yaml
> +        cd {DESTINATION-PATH}/mongodb-bi-osx-{x86_64|arm64}-{version}/
```suggestion
        cd {DESTINATION-PATH}/mongodb-bi-osx-{x86_64|arm64-macos{11|13}}-{version}/
```

2024-06-26 17:37 UTC, nbagnard commented on source/includes/steps-install-bi-connector-rhel.yaml
> +  MongoDB release. MongoDB signs each release branch with a different
```suggestion
  MongoDB release. The `bi-connector.asc` key to validate the BI Connector is available on [pgp.mongodb.com](https://pgp.mongodb.com/bi-connector.asc)  
```

2024-06-26 17:37 UTC, nbagnard commented on source/includes/steps-install-bi-connector-rhel.yaml
> +        curl -LO https://info-mongodb-com.s3.amazonaws.com/mongodb-bi/v2/mongodb-bi-linux-{arch}-{platform}-{version}.tgz.sig
Maybe we could add an example here. I think it won't be super straightforward for users to figure out the arch and platform.
Here is an example link `https://info-mongodb-com.s3.amazonaws.com/mongodb-bi/v2/mongodb-bi-linux-x86_64-rhel90-v2.14.14.tgz.sig`

2024-06-27 19:22 UTC, nbagnard requested changes
I just notice a few little things off, but otherwise it's looking good.

2024-06-27 19:22 UTC, nbagnard commented on source/includes/steps-install-bi-connector-macos.yaml
> +        gpg --verify mongodb-bi-osx-{x86_64|arm64}-{version}.zip.sig mongodb-bi-osx-{x86_64|arm64}-{version}.zip
We missed that one.
```suggestion
        gpg --verify mongodb-bi-osx-{x86_64|arm64-macos{11|13}}-{version}.zip.sig mongodb-bi-osx-{x86_64|arm64-macos{11|13}}-{version}.zip
```

2024-06-27 19:22 UTC, nbagnard commented on source/includes/steps-install-bi-connector-rhel.yaml
> +  MongoDB release. The `bi-connector.asc` key to validate the BI Connector is available on [pgp.mongodb.com](https://pgp.mongodb.com/bi-connector.asc)
The link look odd on the staging page.
<img width="775" alt="image" src="https://github.com/mongodb/docs-bi-connector/assets/91975317/584c01c9-06f6-4484-81bc-4e0d3b550ac2">

2024-06-27 19:22 UTC, nbagnard commented on source/includes/steps-install-bi-connector-debian.yaml
> +  MongoDB release. The `bi-connector.asc` key to validate the BI Connector is available on [pgp.mongodb.com](https://pgp.mongodb.com/bi-connector.asc)
The link look odd on the staging page.
<img width="775" alt="image" src="https://github.com/mongodb/docs-bi-connector/assets/91975317/584c01c9-06f6-4484-81bc-4e0d3b550ac2">

2024-06-28 17:39 UTC, kyuan-mongodb approved these changes
LGTM!

2024-06-28 17:40 UTC, nbagnard approved these changes
LGTM!

2024-07-09 19:16 UTC, jchemburkar approved these changes

2024-07-09 19:38 UTC, merged