DOCSP-38906 Create and Update BIC ODBC Driver workaround
mongodb/docs-bi-connector pull request #441
Opened 2024-08-29 15:40 UTC by kanchana-mongodb

- https://jira.mongodb.org/browse/DOCSP-38906
- Stage:
- Build Log:

2024-08-30 21:24 UTC, bucaojit requested changes
@kanchana-mongodb A more generic section would be better.  The instructions I had in BI-2883 were more for our benefit of documenting how to reproduce it.  I added a suggestion that you can update for the document.

2024-08-30 21:24 UTC, bucaojit commented on source/reference/odbc-driver.txt
> +Workaround for Unsupported Platforms
Let's keep this more general, that way we will not need to update the values or the instructions if things change. 

I'd suggest something like:

- Install the MySQL Cleartext Authentication plugin for your platform.
- Download and install the Oracle MySQL ODBC driver compatible with your platform from the [MySQL Connector/ODBC Downloads page](https://dev.mysql.com/downloads/connector/odbc/).
- Prior to connecting, ensure that the Cleartext plugin is enabled.

2024-09-05 22:03 UTC, bucaojit approved these changes
LGTM

2024-09-06 20:35 UTC, corryroot approved these changes
LGTM!

2024-09-06 20:36 UTC, merged