(DOCSP-43804)(DOCSP-43803)(DOCSP-43802) BI connector release notes for 2.14.14, 2.14.15, and 2.14.16
mongodb/docs-bi-connector pull request #443
Opened 2024-09-27 11:24 UTC by sarahsimpers

[DOCSP 1](https://jira.mongodb.org/browse/DOCSP-43804)
[DOCSP 2](https://jira.mongodb.org/browse/DOCSP-43803)
[DOCSP 3](https://jira.mongodb.org/browse/DOCSP-43802)

2024-09-27 15:35 UTC, nbagnard requested changes

2024-09-27 15:35 UTC, nbagnard commented on source/release-notes.txt
> +  is unsupported for MongoDB versions 7.0 and earlier, and returns ``null``.
Now that I see it, I think this is too much details for the release notes.
There are no user facing changes so let's just not get into the details and remove this section.
```suggestion
```

2024-10-01 11:15 UTC, sarahsimpers commented on source/release-notes.txt
> +  is unsupported for MongoDB versions 7.0 and earlier, and returns ``null``.
@nbagnard Sorry for the delay, I removed this, please take another look when you have a moment and I can merge these in. Thanks!

2024-10-01 11:17 UTC, sarahsimpers commented
Rebased to resolve merge conflicts because other release notes were added while this PR was in progress

2024-10-01 15:43 UTC, nbagnard approved these changes
LGTM!

2024-10-01 17:34 UTC, merged